=== jamnikhana/label-sync/packages/label-sync/src/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "JSON schema for github labels configuration.",
  "properties": {
    "strict": {
      "type": "boolean"
    },
    "labels": {
      "additionalProperties": {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "description": { "type": "string" },
              "color": { "type": "string" }
            },
            "required": ["color"]
          },
          {
            "type": "string"
          }
        ]
      }
    },
    "repositories": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "paths": { "type": "string" },
            "labels": {
              "additionalProperties": {
                "strict": {
                  "type": "boolean"
                },
                "labels": {
                  "additionalProperties": {
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "description": { "type": "string" },
                          "color": { "type": "string" }
                        },
                        "required": ["color"]
                      },
                      {
                        "type": "string"
                      }
                    ]
                  }
                }
              }
            },
            "strict": { "type": "boolean" }
          },
          "required": ["paths"]
        }
      ]
    },
    "publish": {
      "properties": {
        "branch": { "type": "string" }
      }
    }
  },
  "required": ["labels"],
  "additionalProperties": false
}

=== jamnikhana/label-sync/packages/github-labels/src/tests/__fixtures__/labels.config.json
{
  "strict": false,
  "labels": {
    "FAQ": "blue",
    "kind/bug": {
      "color": "yellow",
      "description": "All issues which are bugs."
    }
  },
  "repositories": [
    "prisma/*",
    {
      "paths": "prisma/one-*",
      "labels": {
        "Feature: Prisma One": "green",
        "field/express": {
          "color": "red",
          "description": "Issues related to ExpressJS."
        }
      },
      "strict": true
    },
    {
      "paths": "prisma/two-*",
      "labels": {
        "Feature: Prisma Two": "green",
        "field/express": {
          "color": "red",
          "description": "Issues related to ExpressJS."
        }
      }
    },
    {
      "paths": "prisma/three-*"
    }
  ],
  "publish": {
    "branch": "master"
  }
}
